# RabbitMQ Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "slack-fastapi"
  name: "slack-fastapi-rmq"
spec:
  selector:
    matchLabels:
      app: "slack-fastapi-rmq"
  template:
    metadata:
      labels:
        app: "slack-fastapi-rmq"
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3.9.16-alpine
        startupProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_running", "-q"]
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 10
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        resources:
          limits:
            memory: "200Mi"
            cpu: "250m"
        ports:
        - containerPort: 5672
          name: amqp

# RabbitMQ Service
---
apiVersion: v1
kind: Service
metadata:
  namespace: "slack-fastapi"
  name: "slack-fastapi-rmq-service"
spec:
  selector:
    app: "slack-fastapi-rmq"
  ports:
  - port: 5672
    targetPort: amqp

# RabbitMQ Exporter Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
  namespace: slack-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
    spec:
      containers:
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9419
        env:
        - name: RABBITMQ_URL
          value: "http://slack-fastapi-rmq-service:15672" # Change if Management Plugin Port is different
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
