# RabbitMQ Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "slack-fastapi"
  name: "slack-fastapi-rmq"
spec:
  selector:
    matchLabels:
      app: "slack-fastapi-rmq"
  template:
    metadata:
      labels:
        app: "slack-fastapi-rmq"
    spec:
      containers:
      - name: rabbit
        # command: ["rabbitmq-plugins"]
        # args: ["enable", "rabbitmq_management"]
        # image: rabbitmq:3.9.16-alpine
        image: thinkco/rabbitmq:3.8.2
        startupProbe:
          exec:
            command: ["rabbitmq-diagnostics", "check_running", "-q"]
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 10
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: ${RABBITMQ_USER}
        - name: RABBITMQ_DEFAULT_PASS
          value: ${RABBITMQ_PASSWORD}
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management

# RabbitMQ Service
---
apiVersion: v1
kind: Service
metadata:
  namespace: "slack-fastapi"
  name: "slack-fastapi-rmq-service"
spec:
  selector:
    app: "slack-fastapi-rmq"
  ports:
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: management
    port: 15672
    targetPort: management

# RabbitMQ Exporter Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
  namespace: slack-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
    spec:
      containers:
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9419
        env:
        - name: RABBITMQ_URL
          value: "http://slack-fastapi-rmq-service:15672" # Change if Management Plugin Port is different
        - name: RABBITMQ_USER
          value: ${RABBITMQ_USER}
        - name: RABBITMQ_PASSWORD
          value: ${RABBITMQ_PASSWORD}
