stages:
- "test"
- "clean"
- "build"
- "staging"
- "deploy"

# Build template definition
.build-template: &build_definition
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/deploy/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --verbosity=debug
  tags:
    - kubernetes-runner

services:
- name: docker:dind
  alias: docker
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs/client"

.kube-context:
  image: bitnami/kubectl:latest
  tags:
    - kubernetes-runner
    - deploy-runner

.initial-setup:
  stage: test
  image: python:3.10.8-slim-buster
  tags:
    - docker-runner
  except:
    - tags
  variables:
    PIP_DEFAULT_TIMEOUT: 300
  before_script:
    - apt-get update && apt-get install -y curl gnupg
    - pip install poetry==1.7.1 Jinja2
    - poetry config virtualenvs.create false
    - poetry install
  # artifacts:
  #   paths:
  #     - ./deploy/kube/*.yml

black:
  when: manual
  extends:
  - .initial-setup
  script:
  - black --check .

flake8:
  when: manual
  extends:
  - .initial-setup
  script:
  - flake8 --count .

mypy:
  when: manual
  extends:
  - .initial-setup
  script:
  - mypy .


pytest:
  stage: test
  extends:
    - .initial-setup
  services:
    - name: postgres:13.8-bullseye
      alias: database
  variables:
    SLACK_FASTAPI_DB_BASE: "slack_fastapi_test"
    SLACK_FASTAPI_DB_HOST: database
    POSTGRES_PASSWORD: slack_fastapi
    POSTGRES_USER: slack_fastapi
    POSTGRES_DB: slack_fastapi
  before_script:
    - apt-get update -y
    - apt-get install -y libgl1-mesa-dev libgtk2.0-0 wait-for-it ffmpeg
    - pip install poetry==1.7.1 Jinja2
    - poetry config virtualenvs.create false
  script:
    - poetry install
    - wait-for-it -t 180 $SLACK_FASTAPI_DB_HOST:5432
    - pytest -vv --junitxml=report.xml --cov="slack_fastapi" .
    - ls -la
    - coverage xml

  artifacts:
    when: always
    reports:
      junit: report.xml

stage-clean:
  stage: clean
  extends:
  - .kube-context
  script:
    - rm ./deploy/kube/namespace.yml
    - kubectl apply -f ./deploy/kube
  environment:
    name: staging
  when: manual
  dependencies:
    - pytest

clean:
  stage: clean
  extends:
  - .kube-context
  script:
    - rm ./deploy/kube/namespace.yml
    - kubectl apply -f ./deploy/kube
  environment:
    name: production
  when: manual
  dependencies:
    - pytest

# Pre-Build stage for processing Jinja templates
process-stage-templates:
  stage: staging
  image: python:3.10.8-slim-buster
  script:
    - pip install Jinja2
    - python jinja_processing.py --num_replicas=2 --namespace=staging

process-prod-templates:
  stage: deploy
  image: python:3.10.8-slim-buster
  script:
    - pip install Jinja2
    - python jinja_processing.py --num_replicas=2 --namespace=production

# Build stages for different environments
stage-build:
  <<: *build_definition
  environment:
    name: staging
  variables:
    IMAGE_TAG: "staging-${CI_COMMIT_REF_SLUG}"

build:
  <<: *build_definition
  environment:
    name: production
  variables:
    IMAGE_TAG: "production-${CI_COMMIT_REF_SLUG}"

staging:
  stage: staging
  extends:
  - .kube-context
  script:
    - kubectl config get-contexts
    - kubectl delete job slack-fastapi-migrator -n slack-fastapi --ignore-not-found
    - kubectl apply -f ./deploy/kube/namespace.yml
    - kubectl apply -f ./deploy/kube/db.yml
    - kubectl apply -f ./deploy/kube/app.yml
    - kubectl apply -f ./deploy/kube/rabbit.yml
  only:
    - tags
  dependencies:
    - pytest
    - process-stage-templates

deploy:
  stage: deploy
  extends:
  - .kube-context
  script:
    - kubectl config get-contexts
    - kubectl delete job slack-fastapi-migrator -n slack-fastapi --ignore-not-found
    - kubectl apply -f ./deploy/kube/namespace.yml
    - kubectl apply -f ./deploy/kube/db.yml
    - kubectl apply -f ./deploy/kube/app.yml
    - kubectl apply -f ./deploy/kube/rabbit.yml
  # --context $KUBE_CONTEXT
  only:
    - main
  dependencies:
    - pytest
    - process-prod-templates

# Stop tasks for staging and production environments
stage-stop:
  stage: staging
  image: python:3.10.8-slim-buster
  script:
    - pip install Jinja2
    - python jinja_processing.py --num_replicas=0 --namespace=staging
  dependencies:
    - pytest
  only:
    - tags
  when: manual

stop:
  stage: deploy
  image: python:3.10.8-slim-buster
  script:
    - pip install Jinja2
    - python jinja_processing.py --num_replicas=0 --namespace=production
  dependencies:
    - pytest
  only:
    - main
  when: manual
