gitops:
 manifest_projects:
 - id: slackfastapi/slackfastapi:gitlab-agent
   default_namespace: gitlab
   paths:
   - glob: './deploy/kube/namespace.yaml'
   - glob: './deploy/kube/app.yaml'
   - glob: './deploy/kube/db.yaml'
   - glob: './deploy/kube/rabbit.yaml'
observability:
 logging:
   level: debug
