version: '3.10'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      args:
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          SLACK_FASTAPI_DB_USER: ${SLACK_FASTAPI_DB_USER}
          SLACK_FASTAPI_DB_PASS: ${SLACK_FASTAPI_DB_PASSWORD}
          RABBITMQ_USER: ${RABBITMQ_USER}
          RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    image: slack_fastapi:${SLACK_FASTAPI_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SLACK_FASTAPI_HOST: 0.0.0.0
      SLACK_FASTAPI_PORT: 8000
      SLACK_FASTAPI_DB_USER: ${SLACK_FASTAPI_DB_USER}
      SLACK_FASTAPI_DB_PASS: ${SLACK_FASTAPI_DB_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
    - "8000:8000"
