version: '3.10'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SLACK_FASTAPI_RELOAD: "True"
      SLACK_FASTAPI_DB_USER: ${SLACK_FASTAPI_DB_USER}
      SLACK_FASTAPI_DB_PASS: ${SLACK_FASTAPI_DB_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
