FROM python:3.10.8-slim-buster
RUN apt-get update \
  && apt-get install -y gcc \
  && apt-get install -y ffmpeg libsm6 libxext6 \
  && rm -rf /var/lib/apt/lists/*


RUN pip install poetry==1.5.1

# Configuring poetry
RUN poetry config virtualenvs.create false

# Copying requirements of a project
COPY pyproject.toml poetry.lock /app/src/
WORKDIR /app/src

# Installing requirements
RUN poetry install
# Removing gcc
RUN apt-get purge -y \
  gcc \
  && rm -rf /var/lib/apt/lists/*

# Copying actuall application
COPY . /app/src/
RUN poetry install

CMD ["/usr/local/bin/python", "-m", "slack_fastapi"]
