---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-self
  labels:
    app: kube-prom-stack-prometheus
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      operator.prometheus.io/name: kube-prom-stack-kube-prome-prometheus

---
# ServiceMonitor for FastAPI
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: prometheus
  labels:
    team: frontend
spec:
  selector:
    # matchLabels: {}
    matchLabels:
      app: slack-fastapi-app
  namespaceSelector:
    matchNames:
      - slack-fastapi
  endpoints:
    - port: "8000"
      interval: 60s
      path: "/metrics"

---
# ServiceMonitor for Postgres Exporter
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: postgres-exporter
  namespaceSelector:
    matchNames:
      - slack-fastapi
  endpoints:
  - port: "9187"
    interval: 60s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: rabbitmq-exporter
  namespaceSelector:
    matchNames:
      - slack-fastapi
  endpoints:
  - port: "9419"
    interval: 60s

---
# Ingress for Prometheus
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    name: prometheus
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  rules:
    - host: prometheus.redevops.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prom-stack-kube-prome-prometheus
                port:
                  number: 9090
  tls:
    - hosts:
        - prometheus.redevops.io
      secretName: prometheus-tls

---
# Ingress for Grafana
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: prometheus
  labels:
    name: grafana
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  rules:
    - host: grafana.redevops.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kube-prom-stack-grafana
                port:
                  number: 80
  tls:
    - hosts:
        - grafana.redevops.io
      secretName: grafana-tls
---
# to re-apply it since traefik was not running at the time it was applied the first time
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack-fastapi-app
  namespace: slack-fastapi
  labels:
    name: slack-fastapi-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # for DO
    # cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    # for YC
    cert-manager.io/cluster-issuer: "yc-clusterissuer"
spec:
  rules:
    - host: api.redevops.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: slack-fastapi-app-service
                port:
                  number: 80
  tls:
    - hosts:
        - api.redevops.io
      secretName: api-redevops-io-tls

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: loki
#   namespace: prometheus
#   labels:
#     name: loki
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.tls: "true"
#     cert-manager.io/cluster-issuer: "yc-clusterissuer"
# spec:
#   rules:
#     - host: loki.redevops.io
#       http:
#         paths:
#           - pathType: Prefix
#             path: "/"
#             backend:
#               service:
#                 name: loki-gateway
#                 port:
#                   number: 80
#   tls:
#     - hosts:
#         - loki.redevops.io
#       secretName: loki-tls
