"""fixes

Revision ID: b685184f05d8
Revises: f3dc7e8a9d3a
Create Date: 2022-10-25 18:10:32.478574

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b685184f05d8"
down_revision = "f3dc7e8a9d3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clips",
        sa.Column("video_key", sa.String(length=1000), nullable=False),
    )
    op.drop_column("clips", "video_path")
    op.add_column(
        "user_clip_settings",
        sa.Column("sound_check", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_clip_settings", "sound_check")
    op.add_column(
        "clips",
        sa.Column(
            "video_path",
            sa.VARCHAR(length=1000),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("clips", "video_key")
    # ### end Alembic commands ###
