"""revork

Revision ID: 3d8ba25783a7
Revises: 960f5b96093f
Create Date: 2022-10-16 20:00:05.310032

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3d8ba25783a7"
down_revision = "960f5b96093f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_clip_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("max_seconds_lenght", sa.Integer(), nullable=True),
        sa.Column("model_threshold", sa.Float(), nullable=True),
        sa.Column("median_hit_modificator", sa.Float(), nullable=True),
        sa.Column("noice_threshold", sa.String(length=200), nullable=True),
        sa.Column("audio_threshold", sa.String(length=200), nullable=True),
        sa.Column("crop_interval", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "video_properties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.Column("frame_width", sa.Integer(), nullable=False),
        sa.Column("frame_height", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("video_properties", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("video_path", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_clips_users_id_user"),
        sa.ForeignKeyConstraint(
            ["video_properties"],
            ["video_properties.id"],
            name="fk_clips_video_properties_id_video_properties",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("video_properties", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("video_path", sa.String(length=1000), nullable=True),
        sa.Column("audio_path", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_videos_users_id_user"),
        sa.ForeignKeyConstraint(
            ["video_properties"],
            ["video_properties.id"],
            name="fk_videos_video_properties_id_video_properties",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("users_properties")
    op.add_column("users", sa.Column("clip_settings", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_users_user_clip_settings_id_clip_settings",
        "users",
        "user_clip_settings",
        ["clip_settings"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_users_user_clip_settings_id_clip_settings",
        "users",
        type_="foreignkey",
    )
    op.drop_column("users", "clip_settings")
    op.create_table(
        "users_properties",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "max_seconds_lenght",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "model_threshold",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "median_hit_modificator",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "noice_threshold",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "audio_threshold",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "crop_interval",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_users_properties_users_id_user",
        ),
        sa.PrimaryKeyConstraint("id", name="users_properties_pkey"),
    )
    op.drop_table("videos")
    op.drop_table("clips")
    op.drop_table("video_properties")
    op.drop_table("user_clip_settings")
    # ### end Alembic commands ###
