"""ClipSettingsFix

Revision ID: 1dd249a2747a
Revises: b685184f05d8
Create Date: 2022-10-25 18:15:15.223252

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1dd249a2747a"
down_revision = "b685184f05d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_clip_settings",
        sa.Column("trained_model", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_clip_settings", "trained_model")
    # ### end Alembic commands ###
