"""auth

Revision ID: 960f5b96093f
Revises: 2b7380507a71
Create Date: 2022-10-12 18:18:30.928341

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "960f5b96093f"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column("exp", sa.Integer(), nullable=False),
        sa.Column("iat", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=True),
        sa.Column("code", sa.String(length=4), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "users_properties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("max_seconds_lenght", sa.Integer(), nullable=False),
        sa.Column("model_threshold", sa.Float(), nullable=False),
        sa.Column("median_hit_modificator", sa.Float(), nullable=False),
        sa.Column("noice_threshold", sa.String(length=200), nullable=False),
        sa.Column("audio_threshold", sa.String(length=200), nullable=False),
        sa.Column("crop_interval", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_users_properties_users_id_user",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_properties")
    op.drop_table("users")
    op.drop_table("revoked_tokens")
    # ### end Alembic commands ###
