"""videos_datetime

Revision ID: 427f08d15923
Revises: 1dd249a2747a
Create Date: 2023-06-29 00:14:14.903596

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "427f08d15923"
down_revision = "1dd249a2747a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("uploaded", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "uploaded")
    # ### end Alembic commands ###
