"""user_setup_field

Revision ID: 7ccd509f61fc
Revises: 3c06a9654a63
Create Date: 2023-07-24 11:09:57.415045

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ccd509f61fc"
down_revision = "3c06a9654a63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("set_up", sa.Boolean(), nullable=True))
    op.alter_column("users", "role", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.drop_column("users", "set_up")
    # ### end Alembic commands ###
